version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cepdb
      MYSQL_USER: cepuser
      MYSQL_PASSWORD: ceppass
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - cep-network

  cep-api:
    build: .
    container_name: cep-api
    ports:
      - "8080:8080"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/cepdb
      SPRING_DATASOURCE_USERNAME: cepuser
      SPRING_DATASOURCE_PASSWORD: ceppass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - cep-network

volumes:
  mysql-data:

networks:
  cep-network:

